In [1]:
import numpy as np

In [3]:
A = np.array([[1,1,0,0],[0,1,1,0],[0,0,1,1],[1,0,0,1]])
B = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])

In [6]:
print(np.linalg.inv(B))


[[ 1. -1.  0.  0.]
 [ 0.  1. -1.  0.]
 [ 0.  0.  1. -1.]
 [ 0.  0.  0.  1.]]


In [10]:
np.dot(A,np.linalg.inv(B))

array([[ 1.,  0., -1.,  0.],
       [ 0.,  1.,  0., -1.],
       [ 0.,  0.,  1.,  0.],
       [ 1., -1.,  0.,  1.]])

In [16]:
A = np.array([[0,1],[-1,0]])
np.linalg.eig(A)

(array([0.+1.j, 0.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        +0.70710678j, 0.        -0.70710678j]]))

In [19]:
A = np.array([[3,3,0],[1,3,1],[0,1,3]])
np.linalg.eig(A)

(array([1., 5., 3.]),
 array([[-8.01783726e-01, -8.01783726e-01, -7.07106781e-01],
        [ 5.34522484e-01, -5.34522484e-01, -2.15949179e-16],
        [-2.67261242e-01, -2.67261242e-01,  7.07106781e-01]]))

In [24]:
A = np.array([[1,2,1,0],[2,2,3,3],[0,0,3,0],[-1,2,3,4]])
sum(np.linalg.eig(A)[0])

10.0

In [26]:
A = np.array([[0,1],[0,0]])
np.linalg.eig(A)

(array([0., 0.]),
 array([[ 1.00000000e+000, -1.00000000e+000],
        [ 0.00000000e+000,  2.00416836e-292]]))

In [28]:
A = np.array([[1,1],[1,0]])
np.linalg.eig(A)

(array([ 1.61803399, -0.61803399]),
 array([[ 0.85065081, -0.52573111],
        [ 0.52573111,  0.85065081]]))

In [46]:
A = np.array([[0,0,0.5,0,1],[0.5,0,0,0,0],[0.5,0.5,0,0,0],[0,0,0.5,0,0],[0,0.5,0,1,0]])
print(A)
v,w = np.linalg.eig(A)

[[0.  0.  0.5 0.  1. ]
 [0.5 0.  0.  0.  0. ]
 [0.5 0.5 0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.5 0.  1.  0. ]]


In [47]:
print(v)

[ 1.        +0.j         -0.02165772+0.61359282j -0.02165772-0.61359282j
 -0.47834228+0.32059983j -0.47834228-0.32059983j]


In [48]:
print(w)

[[ 0.65319726+0.j          0.1449275 -0.44675181j  0.1449275 +0.44675181j
   0.66234864+0.j          0.66234864-0.j        ]
 [ 0.32659863+0.j         -0.36775609-0.10511693j -0.36775609+0.10511693j
  -0.47773458-0.32019253j -0.47773458+0.32019253j]
 [ 0.48989795+0.j         -0.4427421 +0.19720419j -0.4427421 -0.19720419j
  -0.28794469+0.1417003j  -0.28794469-0.1417003j ]
 [ 0.24494897+0.j          0.17321474+0.35466454j  0.17321474-0.35466454j
   0.27618765+0.03699352j  0.27618765-0.03699352j]
 [ 0.40824829+0.j          0.49235595+0.j          0.49235595-0.j
  -0.17285702+0.14149871j -0.17285702-0.14149871j]]


In [54]:
B = w[:,0]
C = np.array([[1.6,0.8,1.2,0.6,1]])
B/C
print(B)
print(C)

[0.65319726+0.j 0.32659863+0.j 0.48989795+0.j 0.24494897+0.j
 0.40824829+0.j]
[[1.6 0.8 1.2 0.6 1. ]]


In [59]:
A = np.array([[10,21,30],[25,35,45],[15,30,45]])
np.dot(A,2)
print(np.linalg.det(A))
print(np.linalg.det(np.dot(A,2)))

-450.00000000000006
-3599.999999999998


In [61]:
np.linalg.det(np.dot(A,2))/np.linalg.det(A)

7.999999999999995

In [74]:
A = np.array([[23,33,31],[13,20,41]])
print(np.dot(A.T,A))
C = np.dot(A.T,A)
print(np.linalg.det(C))

[[ 698 1019 1246]
 [1019 1489 1843]
 [1246 1843 2642]]
-2.3288627468067387e-08


In [77]:
A = np.array([[5,3],[7,5]])
B = A.T
C = np.dot(B,A)
print(np.linalg.det(C))

16.000000000000078
