#### Checking for linear independence of a set of vectors
If you are given say n vectors  ($v_1, v_2, v_3, v_4 ... v_n$) and are asked to check if these vectors are linearly independent. An easy way to do the same is to use the fundamental definition of linear independence:

$x_1.v_1 + x_2.v_2 + x_3.v_3 .... x_n.v_n$ = 0, where at-least one of the $x_1, x_2, x_3 ... x_n$ should be non-zero.

Writing this in the matrix form becomes:
$\begin{bmatrix} v_{1,1} \\ v_{2,1}  \\ v_{3,1} \end{bmatrix}$ . $x_1$ + $\begin{bmatrix} v_{1,2} \\ v_{2,2}  \\ v_{3,2} \end{bmatrix}$ . $x_2$ ... $\begin{bmatrix} v_{1,n} \\ v_{2,n}  \\ v_{3,n} \end{bmatrix}$ . $x_2$ = 0.

Where $v_{1,1}, v_{2,1}$ ... etc are elements of vector $v_1$ so on.
<br>**Note**: We have used here a 3 elements in each vector this argument can be extended to any length (I Was too lazy to type a nXn vector).  

This in form of matrix multiplication can be written as:

$\begin{bmatrix} v_{1,1} & v_{1,2} & ... & v_{1,n} \\ v_{2,1} & v_{2,2} & ... & v_{2,n}  \\ v_{3,1} & v_{3,2} & ... & v_{3,n} \end{bmatrix}$ . $\begin{bmatrix} x_1 \\ x_2 \\x_3 \\... \\ x_n \end{bmatrix}$ 

<br> This will be a 3X1 matrix and which can be seen to be the equation we wrote above. Now if the determinant of this matrix V is 0 then the vectors are not linearly independent. Let us take an example. 

Question: To check if 3 vectors $v_1 = \begin{bmatrix} 1 \\ 2  \\ 3 \end{bmatrix}, v_2 = \begin{bmatrix} 1 \\ 3  \\ 4 \end{bmatrix} and  v_3 = \begin{bmatrix} 3 \\ 8  \\ 11 \end{bmatrix}$ are linearly independent or not?

Using the argument above we will create a matrix which has columns as the elements above and check for the determinant = 0 or not. 
<br> Another way of checking the same is if the rank of the matrix is less than min(Rows, Columns) in the matrix. We will explore both the methods in below codes.

**Note** This will become fundamental for linear equation solution for us. 

In [29]:
import numpy as np
v1 = np.array([[1,2,3]])
v2 = np.array([[1,3,4]])
v3 = np.array([[3,8,11]])
##Whenever declaring an array in numpy we need to use two brackets otherwise it becomes a row of elements.
##This can be checked by using shape argument 
v4 = np.array([1,2,3])
print(v4.shape)
print(v1.shape)
#v4 is a 3 element 1d Array and v1 is 3X1 vector (which is exactly what we are looking for)

(3,)
(1, 3)


In [25]:
V_final = np.concatenate((v1.T,v2.T,v3.T),axis = 1)
#This gives us the matrix required
V_final.shape

(3, 3)

In [28]:
##Now we compute the determinant of this matrix:
print(np.linalg.det(V_final)) 
##This gives us a result which is ~0 which means the vectors are linearly dependent. Other way to check is via rank
print(np.linalg.matrix_rank(V_final))
##The rank is < dimension of the array which means that the vectors are linearly dependent. 

-1.1102230246251573e-16
2


In [33]:
v1 = np.array([[1,1,2,4]])
v2 = np.array([[2,1,1,4]])
v3 = np.array([[5,3,4,12]])
##Whenever declaring an array in numpy we need to use two brackets otherwise it becomes a row of elements.
##This can be checked by using shape argument 
V_final = np.concatenate((v1.T,v2.T,v3.T),axis = 1)
#print(np.linalg.det(V_final))
#Determinant approach will not work in case of non-square matrices. 
print(np.linalg.matrix_rank(V_final))
#Rank approach will work in every case. 

2


**Degree of Freedom in a set of linear equations is $N_{variables}$ - $N_{number Of Linearly Independent Equations}$

#### Matrix Multiplication
In this section we will be covering matrix multiplication. There is a simple command in ```numpy``` to multiply two matrices. 
```np.dot(A,B)``` where A and B are two matrices which can be multiplied means number of columns in A is equal to number of rows in B. 

In [40]:
A = np.array([[1,2,3],[3,4,5]])
print("MATRIX A LOOKS LIKE")
##Remember when we declare the matrix in above form each bracket contains a row of a matrix !!! 
print(A)
B = np.array([[2,3,4,5,6],[6,4,6,7,5],[5,7,8,4,4]])
print("MATRIX B LOOKS LIKE")
print(B)
print("SHAPE OF MATRIX A AND B ARE")
print(A.shape)
print(B.shape)
print("PRODUCT OF THESE TWO MATRIX IS")
print(np.dot(A,B))

MATRIX A LOOKS LIKE
[[1 2 3]
 [3 4 5]]
MATRIX B LOOKS LIKE
[[2 3 4 5 6]
 [6 4 6 7 5]
 [5 7 8 4 4]]
SHAPE OF MATRIX A AND B ARE
(2, 3)
(3, 5)
PRODUCT OF THESE TWO MATRIX IS
[[29 32 40 31 28]
 [55 60 76 63 58]]


In [52]:
##THESE ARE TEST CODES NOT TO BE CONSIDERED
A = np.array([[1,1],[1,2],[1,3]])
B = np.array([[5,0,0]]).T
x1 = np.array([[10,-5]]).T
x2 = np.array([[7,-3]]).T
print(np.linalg.norm(np.dot(A,x1)-B))
#Norm computes the scalar value of any vector essentially detailing the squareroot of sum of squares of individual elements
print(np.linalg.norm(np.dot(A,x2)-B)**2)
np.linalg.norm(A)

5.0
5.999999999999999


4.123105625617661

In [56]:
##THESE ARE TEST CODES NOT TO BE CONSIDERED
for c in [5,16/3,17/3,6]:
    print(f"{c} ---- {np.linalg.norm(np.dot(A,np.array([[c,-2]]).T)-B)}")

5 ---- 2.449489742783178
5.333333333333333 ---- 2.23606797749979
5.666666666666667 ---- 2.1602468994692865
6 ---- 2.23606797749979


#### Solution of Linear Equations
In this section we will try to solve linear equations. Let us take an example:
<br> x + 2y + 3z = 6
<br> 3x + 4y + z = 8
<br> 2x - y + z = 2

This can be written in matrix form as:
$\begin{bmatrix} 1 & 2 & 3 \\ 3 & 4 & 1  \\ 2 & -1 & 1 \end{bmatrix}$ X $\begin{bmatrix} x \\ y  \\ z \end{bmatrix}$ = $\begin{bmatrix} 6 \\ 8  \\ 2 \end{bmatrix}$
<br> This is general form for **Ax = b**

For solution of linear equations we need to understand two key concepts:
1. MATRIX MULTIPLICATION
    <br>a. Matrix multiplication AxB is possible only when number of columns in A = number of rows in B. Formula in python is ```np.dot(A,B)```
2. MATRIX INVERSION 
    <br>a. Matrix Inversion is possible only when - i. The matrix is Square and ii. Determinant of matrix is non-zero. Formula in python is ```np.linalg.inv(A)```

In [57]:
##Matrix Multiplication
A = np.array([[2,0],[1,1]])
B = np.array([[1,1],[0,0]])
print(np.dot(A,B))
print(np.dot(B,A))
##This proves the matrix multiplication is not commutative AxB != BxA

[[2 2]
 [1 1]]
[[3 1]
 [0 0]]


Steps for solving a linear equation:
1. Form a matrix with coefficients call it A
2. Compute inverse of the coefficient matrix $A^{-1}$
3. Create a value matrix (RHS of our equation) call it b
4. Multiply $A^{-1}$ with b to arrive at the solution for each of the variables
<br> Essentially we are trying to solve the equation Ax = b by solving x = $A^{-1}$.b

Let us solve an example in python.
Say our equations are:
<br> x+2y = 0
<br> 2x+5y = -1
<br> Here our value of A is $\begin{bmatrix} 1 & 2 \\ 2 & 5 \end{bmatrix}$ and our b is $\begin{bmatrix} 0 \\ -1 \end{bmatrix}$
<br>Above steps in pythong will look like:
1. Declare A by using ```np.array([[1,2],[2,5]])```
2. Declare b by using ```np.array([[0,-1]]).T```
3. Find inverse of A by using ```np.linalg.inv(A)```
4. Multiply $A^{-1}$ by b using ```np.dot(Ainv,b)```
5. Get values for x and y

In [61]:
#Solution in python
A = np.array([[1,2],[2,5]])
b = np.array([[0,-1]]).T
Ainv = np.linalg.inv(A)
soln = np.dot(Ainv,b)
print(soln)
#Here x = 2 and y = -1

[[ 2.]
 [-1.]]


In [65]:
#Let us try to solve the linear equation in 3 variables we mentioned in the beginning of this section
#x + 2y + 3z = 6; 3x + 4y + z = 8; 2x - y + z = 2
A = np.array([[1,2,3],[3,4,1],[2,-1,1]])
b = np.array([[6,8,2]]).T
soln = np.dot(np.linalg.inv(A),b)
print(soln)
#Here our solution is x= 1 y = 1 and z = 1

[[1.]
 [1.]
 [1.]]


In [67]:
A = np.array([[1,2,3,3],[2,0,6,2],[3,4,9,7]]).T
np.linalg.matrix_rank(A)

2

In [70]:
from sympy import Matrix
A = np.array([[2,5,-3],[1,4,2]])
print(np.linalg.matrix_rank(A))
print(Matrix(Matrix(A).nullspace()))

2
Matrix([[22/3], [-7/3], [1]])


**NOTE: The above methods work only for non-homogeneous equations where $b \neq 0$. However, if b = 0 the above methods will fail and they require more advanced solutions - Singular Value Decomposition which are yet to be covered.**