#### Matrix Multiplication
In this section we will be covering matrix multiplication. There is a simple command in ```numpy``` to multiply two matrices. 
```np.dot(A,B)``` where A and B are two matrices which can be multiplied means number of columns in A is equal to number of rows in B. 

In [40]:
A = np.array([[1,2,3],[3,4,5]])
print("MATRIX A LOOKS LIKE")
##Remember when we declare the matrix in above form each bracket contains a row of a matrix !!! 
print(A)
B = np.array([[2,3,4,5,6],[6,4,6,7,5],[5,7,8,4,4]])
print("MATRIX B LOOKS LIKE")
print(B)
print("SHAPE OF MATRIX A AND B ARE")
print(A.shape)
print(B.shape)
print("PRODUCT OF THESE TWO MATRIX IS")
print(np.dot(A,B))

MATRIX A LOOKS LIKE
[[1 2 3]
 [3 4 5]]
MATRIX B LOOKS LIKE
[[2 3 4 5 6]
 [6 4 6 7 5]
 [5 7 8 4 4]]
SHAPE OF MATRIX A AND B ARE
(2, 3)
(3, 5)
PRODUCT OF THESE TWO MATRIX IS
[[29 32 40 31 28]
 [55 60 76 63 58]]


#### Solution of Linear Equations
In this section we will try to solve linear equations. Let us take an example:
<br> x + 2y + 3z = 6
<br> 3x + 4y + z = 8
<br> 2x - y + z = 2

This can be written in matrix form as:
$\begin{bmatrix} 1 & 2 & 3 \\ 3 & 4 & 1  \\ 2 & -1 & 1 \end{bmatrix}$ X $\begin{bmatrix} x \\ y  \\ z \end{bmatrix}$ = $\begin{bmatrix} 6 \\ 8  \\ 2 \end{bmatrix}$
<br> This is general form for **Ax = b**

For solution of linear equations we need to understand two key concepts:
1. MATRIX MULTIPLICATION
    <br>a. Matrix multiplication AxB is possible only when number of columns in A = number of rows in B. Formula in python is ```np.dot(A,B)```
2. MATRIX INVERSION 
    <br>a. Matrix Inversion is possible only when - i. The matrix is Square and ii. Determinant of matrix is non-zero. Formula in python is ```np.linalg.inv(A)```

In [57]:
##Matrix Multiplication
A = np.array([[2,0],[1,1]])
B = np.array([[1,1],[0,0]])
print(np.dot(A,B))
print(np.dot(B,A))
##This proves the matrix multiplication is not commutative AxB != BxA

[[2 2]
 [1 1]]
[[3 1]
 [0 0]]


Steps for solving a linear equation:
1. Form a matrix with coefficients call it A
2. Compute inverse of the coefficient matrix $A^{-1}$
3. Create a value matrix (RHS of our equation) call it b
4. Multiply $A^{-1}$ with b to arrive at the solution for each of the variables
<br> Essentially we are trying to solve the equation Ax = b by solving x = $A^{-1}$.b

Let us solve an example in python.
Say our equations are:
<br> x+2y = 0
<br> 2x+5y = -1
<br> Here our value of A is $\begin{bmatrix} 1 & 2 \\ 2 & 5 \end{bmatrix}$ and our b is $\begin{bmatrix} 0 \\ -1 \end{bmatrix}$
<br>Above steps in pythong will look like:
1. Declare A by using ```np.array([[1,2],[2,5]])```
2. Declare b by using ```np.array([[0,-1]]).T```
3. Find inverse of A by using ```np.linalg.inv(A)```
4. Multiply $A^{-1}$ by b using ```np.dot(Ainv,b)```
5. Get values for x and y

In [61]:
#Solution in python
A = np.array([[1,2],[2,5]])
b = np.array([[0,-1]]).T
Ainv = np.linalg.inv(A)
soln = np.dot(Ainv,b)
print(soln)
#Here x = 2 and y = -1

[[ 2.]
 [-1.]]


In [65]:
#Let us try to solve the linear equation in 3 variables we mentioned in the beginning of this section
#x + 2y + 3z = 6; 3x + 4y + z = 8; 2x - y + z = 2
A = np.array([[1,2,3],[3,4,1],[2,-1,1]])
b = np.array([[6,8,2]]).T
soln = np.dot(np.linalg.inv(A),b)
print(soln)
#Here our solution is x= 1 y = 1 and z = 1

[[1.]
 [1.]
 [1.]]


In [67]:
A = np.array([[1,2,3,3],[2,0,6,2],[3,4,9,7]]).T
np.linalg.matrix_rank(A)

2

**NOTE: The above methods work only for non-homogeneous equations where $b \neq 0$. However, if b = 0 the above methods will fail and they require more advanced solutions - Singular Value Decomposition which are yet to be covered.**
<br>We will solve two types of equations 
1. Homogeneous Equations
2. Non-Homogeneous Equations

<br>We will also evaluate the conditions of consistency and kind of solutions present. 

##### Homogeneous Systems of Equations
Homogeneous systems of equations are ones where the RHS of the equation is Zero. Example:
<br>2x + 3y + 5z = 0
<br>5x + 4y + 10z = 0
<br>7x + 8y + 9z = 0

Writing in matrix form we have: $\begin{bmatrix} 2 & 3 & 5 \\ 5 & 4 & 10 \\ 7 & 8 & 9 \end{bmatrix}$. $\begin{bmatrix} x \\ y \\z \end{bmatrix}$ = $\begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}$

<br>A few rules to remember here are:
1. If the value of the determinant of coefficient matrix is 0 then there is a trivial solution where x=y=z = 0
2. If the value of the determinant of the coefficient matrix is non-zero then there will be infinite solutions
3. There is no condition where there are no solutions to this equation because x=y=z=0 will always be a solution no matter what happens
<br>We will not be solving non-homogeneous equations at this point in time, we will only check for existence of solutions. 

We can define the solutions in terms of **ranks of the matrices.** The rules for the same are as follows:
1. If Rank(Coefficient_Matrix) = Number of Variables then there is only trivial solution i.e. all variables = 0
2. If Rank(Coefficient_Matrix) < Number of Variables then there are infinite solutions
3. If Number of Equations < Number of Variables then there are infinite solutions (This also implies the Rank of coefficient matrix < Number of Variables)
4. Number of Equations = Number of Variables and Coefficient Determinant = 0 then infinite else only Trivial Solutions

We will take a few examples:
<br>How many solutions following equations will have:
<br> x + 3y -2z = 0
<br> 2x - y + 4z = 0
<br> x - 11y + 14z = 0
<br>Now there are 3 equations and 3 variables two ways to check the solution:
1. If determinant is 0 then there are infinite solutions
2. If rank of coefficient matrix is < min(number of rows or columns) then infinite solutions let us check both

In [7]:
A = np.array([[1,3,-2],[2,-1,4],[1,-11,14]])
det = np.linalg.det(A)
rank = np.linalg.matrix_rank(A)
print(det)
##The value of determinant is 0
print(rank)
##The rank is less the number of variables

##Both the answers point to infinite solutions

4.662936703425667e-15
2


##### Solution of non-homogeneous equations
Non homogeneous equations we have the RHS $\neq$ 0. Which means at-least one of the elements in RHS is non-zero. Now there are following possibilities:
1. Inconsistent Solutions - No Solutions Exist
2. Consistent Solutions - There is a unique solution
3. Consistent Solutions - There are infinite solutions possible
<br>As with homogeneous equations there are two methods to identify the solution category - (i) Determinant & (ii) Rank.
<br>We will discuss each of these methods in this section:

**Determinant Method**: This will work only in case of square matrix i.e. when number of variables = number of equations.
Let us assume we have an equation:
<br>$\large a_{1}x + b_{1}y = c_1$
<br>$\large a_{2}x + b_{2}y = c_2$

When we write this in the matrix form it can be written as:
$\begin{bmatrix} a_1 & b_1 \\ a_2 & b_2 \end{bmatrix}$. $\begin{bmatrix} x \\ y \end{bmatrix}$ = $\begin{bmatrix} c_1 \\ c_2 \end{bmatrix}$. Which can also be written as Ax = b.

<br>Let us define a few determinants:

$\large\Delta$ = $\begin{vmatrix} a_1 & b_1 \\ a_2 & b_2 \end{vmatrix}$ This is the determinant for coefficient matrix. <br>$\large\Delta_1$ = $\begin{vmatrix} c_1 & b_1 \\ c_2 & b_2 \end{vmatrix}$ This is determinant where we replace **a** by RHS values
<br>$\large\Delta_2$ = $\begin{vmatrix} a_1 & c_1 \\ a_2 & c_2 \end{vmatrix}$ This is determinant where we replace **b** by RHS values

Now we will discuss conditions for solutions:
1. If $\Delta \neq 0$ then there is a unique solution to the equation
2. If $\Delta = 0$ then there are two conditions:
    <br>a. If all $\Delta_1 = \Delta_2 = \Delta_3 = 0$ then the equations are consistent and there are infinite solutions
    <br>b. If at-least one of $\Delta_1$ or $\Delta_2$ or $\Delta_3$ is non-zero then the equations are inconsistent and there are no solutions

Also note the solution if it exists is given by:
x = $\large\frac{\Delta_1}{\Delta}$ and y = $\large\frac{\Delta_2}{\Delta}$

Let us take following examples. 
<br>***Example 1:***<br>
2x+3y=5 <br>
7x+5y=10

$\Delta$ = $\begin{vmatrix} 2 & 3 \\ 7 & 5 \end{vmatrix}$ <br>
$\Delta_1$ = $\begin{vmatrix} 5 & 3 \\ 10 & 5 \end{vmatrix}$ <br>
$\Delta_2$ = $\begin{vmatrix} 2 & 5 \\ 7 & 10 \end{vmatrix}$ 

<br>Also note if you have $\Delta \neq 0$ Then you can compute the inverse of A (Coefficient Matrix). Then you can find the solution also by $A^{-1}$.b.
<br>Where A is the matrix of coefficients and b is the vector of RHS values. Again note inverse method works only when the number of equations = number of variables. 

In [38]:
##Solution for example 1
coeff_Mat = np.array([[2,3],[7,5]])
print(coeff_Mat)
delta_1_mat = np.array([[5,3],[10,5]])
print(delta_1_mat)
delta_2_mat = np.array([[2,5],[7,10]])
print(delta_2_mat)
##Now we compute value of each of these determinants
print("Delta = ",np.linalg.det(coeff_Mat))
#As the determinant of coefficient matrix is non zero the equation should have unique solutions
print("Delta 1 = ",np.linalg.det(delta_1_mat))
print("Delta 2 = ",np.linalg.det(delta_2_mat))
x = np.linalg.det(delta_1_mat)/np.linalg.det(coeff_Mat)
y = np.linalg.det(delta_2_mat)/np.linalg.det(coeff_Mat)
print("Value of x = ",x)
print("Value of y = ",y)

##We can check these solutions by putting each of values in x and y
print("LHS of equation 1 evaluates to",2*x+3*y)
print("LHS of equation 2 evaluates to",7*x+5*y)
#This comes equal to the RHS (note Python for that matter any programming language does a floating point computation therefore)
#these values of 4.9999999 and 9.999999. 
#Thus we have proved that these equations have unique solution and computed the solution via determinant method.

[[2 3]
 [7 5]]
[[ 5  3]
 [10  5]]
[[ 2  5]
 [ 7 10]]
Delta =  -11.000000000000002
Delta 1 =  -5.000000000000001
Delta 2 =  -15.0
Value of x =  0.45454545454545453
Value of y =  1.3636363636363633
LHS of equation 1 evaluates to 4.999999999999999
LHS of equation 2 evaluates to 9.999999999999998


<br>***Example 2:***
<br> Test for consistency and solve following system of equations:<br>
2x-3y+7z = 5 <br>
3x+y-3z = 13 <br>
2x+19y-47z = 32 <br>

$\Delta$ = $\begin{vmatrix} 2 & -3 & 7\\ 3 & 1 & -1\\ 2 & 19 & -47 \end{vmatrix}$ <br>
$\Delta_1$ = $\begin{vmatrix} 5 & -3 & 7\\ 13 & 1 & -1\\ 32 & 19 & -47 \end{vmatrix}$ <br>
$\Delta_2$ = $\begin{vmatrix} 2 & 5 & 7\\ 3 & 13 & -1\\ 2 & 32 & -47 \end{vmatrix}$ <br>
$\Delta_3$ = $\begin{vmatrix} 2 & -3 & 5\\ 3 & 1 & 13\\ 2 & 19 & 32 \end{vmatrix}$


In [35]:
#Solution for Example 2
coeff_mat = np.array([[2,-3,7],[3,1,-3],[2,19,-47]])

print("COEFFICIENT MATRIX IS")
print(coeff_mat)
delta_1_mat = np.array([[5,-3,7],[13,1,-1],[32,19,-47]])
print("DELTA 1 IS")
print(delta_1_mat)
delta_2_mat = np.array([[2,5,7],[3,13,-1],[2,32,-47]])
print("DELTA 2 IS")
print(delta_2_mat)
delta_3_mat = np.array([[2,-3,5],[3,1,13],[2,19,32]])
print("DELTA 3 IS")
print(delta_3_mat)

##Now we compute determinants
delta = np.linalg.det(coeff_mat)
print("Value of the coefficient matrix determinant is",det_coeff_mat)
#As the value of determinant of coefficient matrix has turned out to be zero we will check for delta 1 delta 2 and delta 3
delta_1 = np.linalg.det(delta_1_mat)
delta_2 = np.linalg.det(delta_2_mat)
delta_3 = np.linalg.det(delta_3_mat)
print(f"Delta 1 = {delta_1}, Delta 2 = {delta_2}, Delta 3 = {delta_3}")


#All 3 are non-zero and detla is zero means the equations are inconsistent and there is no solution

COEFFICIENT MATRIX IS
[[  2  -3   7]
 [  3   1  -3]
 [  2  19 -47]]
DELTA 1 IS
[[  5  -3   7]
 [ 13   1  -1]
 [ 32  19 -47]]
DELTA 2 IS
[[  2   5   7]
 [  3  13  -1]
 [  2  32 -47]]
DELTA 3 IS
[[ 2 -3  5]
 [ 3  1 13]
 [ 2 19 32]]
Value of the coefficient matrix determinant is -2.747801985947269e-14
Delta 1 = -372.00000000000017, Delta 2 = 27.000000000000096, Delta 3 = 55.000000000000064


**Example 3**
<br>5x+3y+7z = 4
<br>3x+26y+2z =9
<br>7x+2y+10z = 5
<br>We can straight away jump to the solution.

In [37]:
coeff_mat = np.array([[5,3,7],[3,26,2],[7,2,10]])

print("Coefficient matrix is\n",coeff_mat)
delta = np.linalg.det(coeff_mat)
print("Value of determinant of coefficient matrix is",delta)

#Now we again compute delta 1 delta 2 and delta 3

delta_1 = np.linalg.det(np.array([[4,3,7],[9,26,2],[5,2,10]]))

#I have shortened the steps here by computing the determinant directly

delta_2 = np.linalg.det(np.array([[5,4,7],[3,9,2],[7,5,10]]))

delta_3 = np.linalg.det(np.array([[5,3,4],[3,26,9],[7,2,5]]))

print(f"Delta 1 = {delta_1}, Delta 2 = {delta_2}, Delta 3 = {delta_3}")

#All 3 deltas are zero and determinant of coefficient matrix is also zero = the equation has infinite solutions

Coefficient matrix is
 [[ 5  3  7]
 [ 3 26  2]
 [ 7  2 10]]
Value of determinant of coefficient matrix is -1.7167220026489588e-13
Delta 1 = 7.460698725481071e-14, Delta 2 = -5.2910057287850316e-14, Delta 3 = -6.141119359069445e-14


**RANK METHOD OF SOLUTION**
Rank method for determining the consistency of the system of linear equation will work in all the cases (When number of equations is not equal to number of variables also). We compute two ranks here:
1. Rank of Coefficient Matrix A
2. Rank of Augmented matrix which is formed by adding columns of Coefficient Matrix and RHS Values.

In case of our first example:
<br><br>$\large a_{1}x + b_{1}y = c_1$
<br>$\large a_{2}x + b_{2}y = c_2$
<br>Our Coefficient Matrix A = $\begin{bmatrix} a_1 & b_1 \\ a_2 & b_2 \end{bmatrix}$ and our Augmented Matrix will be $\begin{bmatrix} a_1 & b_1 & c_1 \\ a_2 & b_2 & c_2 \end{bmatrix}$ let us call it Aug_A.
<br> Conditions for solution are:
1. If Rank(A) = Rank(Aug_A) then there can be unique solution or infinite solutions:
    <br>a. *Unique Solution* when **Rank(A) = Rank(Aug_A) = Number of Variables**
    <br>b. *Infinite Solutions* when **Rank(A) = Rank(Aug_A) < Number of Variables**
<br>Remember Max of a rank for a mXn matrix is min(m,n) therefore rank can never be greater than number of variables.
2. If **Rank(A) $\neq$ Rank(Aug_A)** then there is *no solution*

<br>In order to find the solution we can use any of the approaches by computation of $\Delta$, $\Delta_1$,... 
<br>Or by computation of $A^{-1}$xb.

<br>Let us check for the consistency and solve the system of equations we solved using determinant method:
<br>***Example 1:***<br>
2x+3y=5 <br>
7x+5y=10

<br>***Example 2:***
<br> Test for consistency and solve following system of equations:<br>
2x-3y+7z = 5 <br>
3x+y-3z = 13 <br>
2x+19y-47z = 32 <br>

**Example 3**
<br>5x+3y+7z = 4
<br>3x+26y+2z =9
<br>7x+2y+10z = 5
<br>We can straight away jump to the solution.


In [43]:
#Solution 1
coeff_mat = np.array([[2,3],[7,5]])
aug_mat = np.array([[2,3,5],[7,5,10]])
rank_coeff_mat = np.linalg.matrix_rank(coeff_mat)
rank_aug_mat = np.linalg.matrix_rank(aug_mat)
print(f"Rank of Coefficient Matrix = {rank_coeff_mat} & Rank of Augmented Matrix = {rank_aug_mat}")
#This shows that the rank of coefficient matrix and augmented matrix is same and is equal to number of variables,
#THE EQUATION HAS UNIQUE SOLUTION

Rank of Coefficient Matrix = 2 & Rank of Augmented Matrix = 2


In [50]:
#Solution 2
coeff_mat = np.array([[2,-3,7],[3,1,-3],[2,19,-47]])
b = np.array([[5,13,32]]).T
aug_mat = np.concatenate((coeff_mat,b),axis=1)
#Instead of typing the matrix again we can concatenate to create augmented matrix
print(aug_mat)
rank_coeff_mat = np.linalg.matrix_rank(coeff_mat)
rank_aug_mat = np.linalg.matrix_rank(aug_mat)
print(f"Rank of Coefficient Matrix = {rank_coeff_mat} & Rank of Augmented Matrix = {rank_aug_mat}")
#Here rank of Coefficient matrix is not equal to rank of augmented matrix => No solution exists

[[  2  -3   7   5]
 [  3   1  -3  13]
 [  2  19 -47  32]]
Rank of Coefficient Matrix = 2 & Rank of Augmented Matrix = 3


In [59]:
#Solution 3
coeff_mat = np.array([[5,3,7],[3,26,2],[7,2,10]])
b = np.array([[4,9,5]]).T
aug_mat = np.concatenate((coeff_mat,b),axis = 1)
rank_coeff_mat = np.linalg.matrix_rank(coeff_mat)
rank_aug_mat = np.linalg.matrix_rank(aug_mat)
print(f"Rank of Coefficient Matrix = {rank_coeff_mat} & Rank of Augmented Matrix = {rank_aug_mat}")
#Here the rank of Coefficient Matrix = Rank of Augmented matrix < Number of Variables => Infinite Solutions

Rank of Coefficient Matrix = 2 & Rank of Augmented Matrix = 2


Let us take one more example of system of equations where we have more equations than variables:
<br>3x+3y+2z = 1
<br>x+2y=4
<br>10y+3z = -2
<br>2x-3y-z = 5
<br>Here we will not be able to use determinant method because the augmented and coefficient matrix are not square. 

In [54]:
coeff_mat = np.array([[3,3,2],[1,2,0],[0,10,3],[2,-3,-1]])
b = np.array([[1,4,-2,5]]).T
aug_mat = np.concatenate((coeff_mat,b),axis = 1)
rank_coeff_mat = np.linalg.matrix_rank(coeff_mat)
rank_aug_mat = np.linalg.matrix_rank(aug_mat)
print(f"Rank of Coefficient Matrix = {rank_coeff_mat} & Rank of Augmented Matrix = {rank_aug_mat}")
#As the rank of Coefficient MAtrix = Rank of Augmented Matrix = Number of Variables => There is a unique solution.
#To solve this equation we need to use advanced matrix computation which is penrose-pseudo inverse or we can use sympy package

Rank of Coefficient Matrix = 3 & Rank of Augmented Matrix = 3


In [57]:
from sympy import *
coeff_matrix = Matrix(coeff_mat)
aug_matrix = Matrix(aug_mat)
print(coeff_matrix.rref())
print(aug_matrix.rref())
#Here look at the last column of the reduced row-echelon form of augmented matrix
#z = -4
#y = 1
#x = 2

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 1, 2))
(Matrix([
[1, 0, 0,  2],
[0, 1, 0,  1],
[0, 0, 1, -4],
[0, 0, 0,  0]]), (0, 1, 2))


Note: You will see a tuple along with RREF output (0,1,2) that is the detail of the pivots and is not relevant for our solution.

This completes our discussion on solution of linear equations using python.

-----

### Read this section for topic of linear independence of vectors
#### Checking for linear independence of a set of vectors
If you are given say n vectors  ($v_1, v_2, v_3, v_4 ... v_n$) and are asked to check if these vectors are linearly independent. An easy way to do the same is to use the fundamental definition of linear independence:

$x_1.v_1 + x_2.v_2 + x_3.v_3 .... x_n.v_n$ = 0, where at-least one of the $x_1, x_2, x_3 ... x_n$ should be non-zero.

Writing this in the matrix form becomes:
$\begin{bmatrix} v_{1,1} \\ v_{2,1}  \\ v_{3,1} \end{bmatrix}$ . $x_1$ + $\begin{bmatrix} v_{1,2} \\ v_{2,2}  \\ v_{3,2} \end{bmatrix}$ . $x_2$ ... $\begin{bmatrix} v_{1,n} \\ v_{2,n}  \\ v_{3,n} \end{bmatrix}$ . $x_2$ = 0.

Where $v_{1,1}, v_{2,1}$ ... etc are elements of vector $v_1$ so on.
<br>**Note**: We have used here a 3 elements in each vector this argument can be extended to any length (I Was too lazy to type a nXn vector).  

This in form of matrix multiplication can be written as:

$\begin{bmatrix} v_{1,1} & v_{1,2} & ... & v_{1,n} \\ v_{2,1} & v_{2,2} & ... & v_{2,n}  \\ v_{3,1} & v_{3,2} & ... & v_{3,n} \end{bmatrix}$ . $\begin{bmatrix} x_1 \\ x_2 \\x_3 \\... \\ x_n \end{bmatrix}$ 

<br> This will be a 3X1 matrix and which can be seen to be the equation we wrote above. Now if the determinant of this matrix V is 0 then the vectors are not linearly independent. Let us take an example. 

Question: To check if 3 vectors $v_1 = \begin{bmatrix} 1 \\ 2  \\ 3 \end{bmatrix}, v_2 = \begin{bmatrix} 1 \\ 3  \\ 4 \end{bmatrix} and  v_3 = \begin{bmatrix} 3 \\ 8  \\ 11 \end{bmatrix}$ are linearly independent or not?

Using the argument above we will create a matrix which has columns as the elements above and check for the determinant = 0 or not. 
<br> Another way of checking the same is if the rank of the matrix is less than min(Rows, Columns) in the matrix. We will explore both the methods in below codes.

**Note** This will become fundamental for linear equation solution for us. 

In [21]:
import numpy as np
v1 = np.array([[1,2,3]])
v2 = np.array([[1,3,4]])
v3 = np.array([[3,8,11]])
##Whenever declaring an array in numpy we need to use two brackets otherwise it becomes a row of elements.
##This can be checked by using shape argument 
v4 = np.array([1,2,3])
print(v4.shape)
print(v1.shape)
#v4 is a 3 element 1d Array and v1 is 3X1 vector (which is exactly what we are looking for)

(3,)
(1, 3)


In [23]:
V_final = np.concatenate((v1.T,v2.T,v3.T),axis = 1)
#This gives us the matrix required
V_final.shape

(3, 3)

In [24]:
##Now we compute the determinant of this matrix:
print(np.linalg.det(V_final)) 
##This gives us a result which is ~0 which means the vectors are linearly dependent. Other way to check is via rank
print(np.linalg.matrix_rank(V_final))
##The rank is < dimension of the array which means that the vectors are linearly dependent. 

-1.1102230246251573e-16
2


In [25]:
v1 = np.array([[1,1,2,4]])
v2 = np.array([[2,1,1,4]])
v3 = np.array([[5,3,4,12]])
##Whenever declaring an array in numpy we need to use two brackets otherwise it becomes a row of elements.
##This can be checked by using shape argument 
V_final = np.concatenate((v1.T,v2.T,v3.T),axis = 1)
#print(np.linalg.det(V_final))
#Determinant approach will not work in case of non-square matrices. 
print(np.linalg.matrix_rank(V_final))
#Rank approach will work in every case. 

2


**Degree of Freedom in a set of linear equations is $N_{variables}$ - $N_{number Of Linearly Independent Equations}$**