***Question Given***
<br>Fit y = $b_1xe^{-b_2x}$
<br>For the following values:
<br>$x_i$ = 1,2,3,4</center>
<br>$y_i$ = 2,4,4,2
<br>In order to solve this I took following approach:
<br> log(y) = log($b_1$) +log(x) -$b_2$x

<br>So I will have the matrix form as follows:
<br>Y = $\begin{bmatrix} log(2) \\ log(4) \\ log(4) \\ log(2) \end{bmatrix}$
<br>
<br>X = $\begin{bmatrix} 1 & log(1) & 1  \\ 1 & log(2) & 2 \\ 1 & log(3) & 3 \\ 1 & log(4) & 4 \end{bmatrix}$
<br>
<br>$\theta$ = $\begin{bmatrix} b_1 \\ b_2 \\ b_3 \end{bmatrix}$

<br>Now my argument for this method was because we know in advance that $b_2$ is 1 which is coefficient of X so once I get the value of $\theta$ I will divide it by scalar $b_2$ and that should give me the value of $b_1$ and $b_3$.

In [1]:
import numpy as np
X = np.array([[1,np.log(1),1],[1,np.log(2),2],[1,np.log(3),3],[1,np.log(4),4]])
Y = np.array([[np.log(2),np.log(4),np.log(4),np.log(2)]]).T

In [2]:
print(X)
print(Y)

[[1.         0.         1.        ]
 [1.         0.69314718 2.        ]
 [1.         1.09861229 3.        ]
 [1.         1.38629436 4.        ]]
[[0.69314718]
 [1.38629436]
 [1.38629436]
 [0.69314718]]


In [3]:
Z = np.dot(X.T,X)
A = np.dot(X.T,Y)
answer = np.dot(np.linalg.inv(Z),A)

In [4]:
answer

array([[ 2.18446489],
       [ 3.30303331],
       [-1.50761941]])

In [5]:
answer_scaled = answer/answer[1]

In [6]:
answer_scaled

array([[ 0.66135115],
       [ 1.        ],
       [-0.45643482]])

Now I can compute $\large e^{b_1}$, I should get value of $b_1$ and $b_3$ is already the $3^{rd}$ element of the answer_scaled array above. However, I do get the right value of $b_3$ from above method. 

**My Questions is why I am not getting the correct value of $b_1$ from this method$