In [1]:
import math

In [8]:
print(math.factorial(6))
import numpy as np

720


In [18]:
A = np.array([[1,3,-2],[4,7,1],[3,-1,12]])
print(A)
print(np.linalg.det(A))
print(np.linalg.matrix_rank(A))

[[ 1  3 -2]
 [ 4  7  1]
 [ 3 -1 12]]
-3.12250225675824e-15
2


In [22]:
A = np.array([[1,2,3],[2,-1,4],[0,5,2]])
print(np.linalg.det(A))

0.0


In [34]:
A = np.array([[1,-3],[1,2]])
print(np.linalg.matrix_rank(A))
print(np.linalg.det(A))

2
4.999999999999999


In [ ]:
p